### PR TITLE
feat: 🎸 update team headshots

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
#### What does this PR do

This PR updates Bolaji and Perrie's headshots on the team page.

#### What are the relevant issues this PR belongs to

#35

### CODE REVIEW

**Review by Princesso — COMMENTED** [review]
Hi @Bolaji, I noticed that this page does not have my image. Could you update it?

**Comment by BolajiAyodeji** [comment]
Sure! But you'd need to reach out to @perriefidelis with your headshots for her to refine. Similar to #35. Once I get the images, I can add them.

**Comment by BolajiAyodeji** [comment]
But till then, you can approve this @Princesso as further changes would come in a later PR when @perriefidelis provides the images.

**Comment by Princesso** [comment]
@perriefidelis here:
https://photos.app.goo.gl/13v1pxKFnfCXjS5e7

**Comment by perriefidelis** [comment]
For records;

Active(https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=4370%3A8437&t=hfpDh1Y8rqVBqrEi-1)
Inactive(https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=4370%3A8438&t=AfRDTtbr9krBFq0I-1)

**Pull request merged**
